name: Build and Push Docker

on:
  push:
  pull_request:

jobs:
  built_and_test_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: fkynjyq/danmaku-server
          tag_with_ref: true
